/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package servidorvotacion;

import java.io.File;

/**
 * Ventana principal del sistema de votación. Desde aquí se controlan las
 * acciones del servidor: iniciar, detener, minar bloques y consultar
 * resultados.
 *
 * También incluye un panel de registro donde se muestran mensajes del sistema y
 * eventos importantes.
 */
public class VentanaServidor extends javax.swing.JFrame {

    private Servidor servidor;

    /**
     * Construye la ventana del servidor. Se encarga de inicializar los
     * elementos gráficos, colocar estado inicial y centrar la interfaz.
     */
    public VentanaServidor() {
        initComponents();

        lblEstado.setText("Servidor detenido");

        txtLog.setEditable(false);

        this.setLocationRelativeTo(null);
    }

    /**
     * Agrega una línea de texto al registro histórico. Incluye fecha y hora
     * para facilitar diagnóstico. Se realiza en el hilo de la interfaz para
     * evitar problemas con la actualización visual.
     */
    public void appendLog(String texto) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            txtLog.append("["
                    + java.time.LocalDateTime.now()
                            .format(java.time.format.DateTimeFormatter
                                    .ofPattern("yyyy-MM-dd HH:mm:ss"))
                    + "] " + texto + "\n");

            txtLog.setCaretPosition(txtLog.getDocument().getLength());
        });
    }

    /**
     * Guarda el registro de eventos en un archivo de texto. No interrumpe el
     * funcionamiento del programa si ocurre un error.
     */
    public void saveLogToFile(File f) {
        try (java.io.FileWriter fw = new java.io.FileWriter(f, true)) {
            fw.write(txtLog.getText());
            fw.flush();
        } catch (Exception e) {
            // Se ignoran errores para evitar bloquear el sistema.
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLevantar = new javax.swing.JButton();
        btnDetener = new javax.swing.JButton();
        btnMinar = new javax.swing.JButton();
        btnResultados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        lblEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLevantar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLevantar.setForeground(new java.awt.Color(0, 204, 0));
        btnLevantar.setText("Iniciar servidor");
        btnLevantar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLevantarActionPerformed(evt);
            }
        });

        btnDetener.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDetener.setForeground(new java.awt.Color(204, 0, 0));
        btnDetener.setText("Detener servidor");
        btnDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetenerActionPerformed(evt);
            }
        });

        btnMinar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMinar.setText("Minar");
        btnMinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinarActionPerformed(evt);
            }
        });

        btnResultados.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnResultados.setText("Resultados");
        btnResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosActionPerformed(evt);
            }
        });

        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtLog.setRows(5);
        jScrollPane1.setViewportView(txtLog);

        lblEstado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEstado.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMinar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLevantar)
                        .addGap(30, 30, 30)
                        .addComponent(btnDetener)
                        .addGap(26, 26, 26)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResultados)
                    .addComponent(btnMinar)
                    .addComponent(btnLevantar)
                    .addComponent(btnDetener))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLevantarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLevantarActionPerformed
        // TODO add your handling code here:
        /**
         * Inicia el servidor si aún no está en ejecución. Cambia el estado
         * visual y registra el evento.
         */

        //servidor = new Servidor(this);
        //servidor.iniciar();
        if (servidor == null) {
            servidor = new Servidor(this); // la clase Servidor que ya tienes
            servidor.iniciar();
            lblEstado.setText("Servidor corriendo");
        } else {
            appendLog("Servidor ya creado.");
        }

    }//GEN-LAST:event_btnLevantarActionPerformed

    private void btnDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetenerActionPerformed
        // TODO add your handling code here:
        /**
         * Detiene el servidor si se encontraba activo. Limpia la referencia y
         * actualiza el estado visual.
         */
        //if (servidor != null) servidor.detener();
        if (servidor != null) {
            servidor.detener();
            servidor = null;
            lblEstado.setText("Servidor detenido");
        } else {
            appendLog("Servidor no está activo.");
        }
    }//GEN-LAST:event_btnDetenerActionPerformed

    private void btnMinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinarActionPerformed
        // TODO add your handling code here:
        /**
         * Ejecuta el proceso de minado en un hilo separado para no congelar la
         * interfaz. Requiere servidor activo.
         */
        /* if (servidor != null) {
            Minador.minar(servidor, this);
        }*/
        if (servidor == null) {
            appendLog("Inicia el servidor primero.");
            return;
        }
        // Ejecutar en hilo para no bloquear la GUI
        new Thread(() -> {
            appendLog("Inicio minado (puede tardar)...");
            Minador.minar(servidor, this); // la clase Minador que añadiremos
        }).start();
    }//GEN-LAST:event_btnMinarActionPerformed

    private void btnResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadosActionPerformed
        // TODO add your handling code here:
        /**
         * Abre una ventana nueva con los resultados actuales. Si el servidor no
         * está encendido, igual intenta mostrarlos en caso de que existan datos
         * cargados previamente.
         */
        //new VentanaResultados(servidor).setVisible(true);
        if (servidor == null) {
            appendLog("Servidor no iniciado. Aun así puedes ver resultados (si hay datos guardados).");
        }
        VentanaResultados vr = new VentanaResultados(servidor);
        vr.setVisible(true);
    }//GEN-LAST:event_btnResultadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaServidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetener;
    private javax.swing.JButton btnLevantar;
    private javax.swing.JButton btnMinar;
    private javax.swing.JButton btnResultados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
